# This is a basic workflow to help you get started with Actions

name: Github-Slack-Integration

# Controls when the workflow will run
on: 
   push:
      paths:
        - 'data/models.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Slack send 
      
      
      - name: Post to a Slack channel
        id: slack
      - uses: technote-space/get-diff-action@v6
      - uses: slackapi/slack-github-action@v1.19.0
        
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          FILES: data/models.json
          FORMAT: json
          run: yarn lint
          if: env.GIT_DIFF
          channel-id: 'C03H68Q1B42'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Actions build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New Model Added: \n${{env.GIT_DIFF}} \n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \nCommit Message: ${{github.event.head_commit.message}}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
    
    
     

          
          
